import { HouseType } from "../redux/catalogSlice";

export const mockHouses : HouseType[] = [
  {
    id: 1,
    photo: ["https://mykaleidoscope.ru/uploads/posts/2021-03/1615571923_51-p-shikarnii-remont-v-kvartire-53.jpg",
  "https://hameleone.ru/wp-content/uploads/f/c/a/fca3c65d9e69bb86b79e914219284487.jpeg"],
    price: "65.00 BYN",
    guest: "2+2",
    room: "1 комн.",
    bed: "3",
    title: "4-комн. апартаменты на Грушевке",
    address: "Заводской р.",
    metro: "Грушевка",
    route: "от Минска (км): 95",
    description:
      `Арендовать дом на сутки в Гомеле с баней и бассейном
в 5 минутах на машине от ЗИПа в усадьбе "Дом у реки". В доме 2-комнаты,
зал для гостей на 10 человек, кухня, ванная, 2 с/у на первом и втором этаже,
сауна, бассейн с холодной`,
    ownerPhoto: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "",
  
  },
  {
    id: 2,
    photo: ["https://euromedbud.com/wp-content/uploads/2022/04/remont-kvartyri-warshawa.jpg"],
    price: "130.00 BYN",
    guest: "2",
    room: "1 комн.",
    bed: "1",
    title: "1-комн. апартаменты на Грушевке",
    address: "Ленинский р.",
    metro: "Пушкинская",
    route: "от Минска (км): 35",
    description:
      `А ещё предприниматели в сети интернет представляют собой не что иное, как квинтэссенцию победы маркетинга над разумом и должны быть функционально разнесены на независимые элементы. Противоположная точка зрения подразумевает, что представители современных социальных резервов ассоциативно распределены по отраслям. Приятно, граждане, наблюдать, как представители современных социальных резервов представляют собой не что иное, как квинтэссенцию победы маркетинга над разумом и должны быть ассоциативно распределены по отраслям.`,
    ownerPhoto: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8cG9ydHJhaXR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    ownerName: "Elena",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "Gold",
  },
  {
    id: 3,
    photo: ["https://hameleone.ru/wp-content/uploads/f/c/a/fca3c65d9e69bb86b79e914219284487.jpeg"],
    price: "35.00 BYN",
    guest: "2+2",
    room: "2 комн.",
    bed: "3",
    title: "Добрая половина выводов одухотворила всех причастных",
    address: "Московский р.",
    metro: "Молодёжная",
    route: "от Минска (км): 95",
    description:
      `Значимость этих проблем настолько очевидна, что убеждённость некоторых оппонентов представляет собой интересный эксперимент проверки благоприятных перспектив. Лишь сторонники тоталитаризма в науке являются только методом политического участия и подвергнуты целой серии независимых исследований. Но тщательные исследования конкурентов неоднозначны и будут разоблачены.`,
    ownerPhoto: "",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "",
  },
  {
    id: 4,
    photo: [],
    price: "90.00 BYN",
    guest: "3",
    room: "2 комн.",
    bed: "3",
    title: "Звук клавиш печатной машинки бодрит",
    address: "Октябрьский р.",
    metro: "Спортивная",
    route: "от Минска (км): 95",
    description:
      `Есть над чем задуматься: ключевые особенности структуры проекта и по сей день остаются уделом либералов, которые жаждут быть указаны как претенденты на роль ключевых факторов. Каждый из нас понимает очевидную вещь: экономическая повестка сегодняшнего дня создаёт необходимость включения в производственный план целого ряда внеочередных мероприятий с учётом комплекса своевременного выполнения сверхзадачи. Современные технологии достигли такого уровня, что современная методология разработки в значительной степени обусловливает важность позиций, занимаемых участниками в отношении поставленных задач.`,
    ownerPhoto: "",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "Gold",
  },
  {
    id: 5,
    photo: ["https://mykaleidoscope.ru/uploads/posts/2021-03/1615571923_51-p-shikarnii-remont-v-kvartire-53.jpg",
  "https://hameleone.ru/wp-content/uploads/f/c/a/fca3c65d9e69bb86b79e914219284487.jpeg"],
    price: "65.00 BYN",
    guest: "2+2",
    room: "1 комн.",
    bed: "3",
    title: "4-комн. апартаменты на Грушевке",
    address: "Заводской р.",
    metro: "Грушевка",
    route: "от Минска (км): 95",
    description:
      `Арендовать дом на сутки в Гомеле с баней и бассейном
в 5 минутах на машине от ЗИПа в усадьбе "Дом у реки". В доме 2-комнаты,
зал для гостей на 10 человек, кухня, ванная, 2 с/у на первом и втором этаже,
сауна, бассейн с холодной`,
    ownerPhoto: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "",
  },
  {
    id: 6,
    photo: [],
    price: "130.00 BYN",
    guest: "2",
    room: "1 комн.",
    bed: "1",
    title: "1-комн. апартаменты на Грушевке",
    address: "Ленинский р.",
    metro: "Пушкинская",
    route: "от Минска (км): 35",
    description:
      `А ещё предприниматели в сети интернет представляют собой не что иное, как квинтэссенцию победы маркетинга над разумом и должны быть функционально разнесены на независимые элементы. Противоположная точка зрения подразумевает, что представители современных социальных резервов ассоциативно распределены по отраслям. Приятно, граждане, наблюдать, как представители современных социальных резервов представляют собой не что иное, как квинтэссенцию победы маркетинга над разумом и должны быть ассоциативно распределены по отраслям.`,
    ownerPhoto: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8cG9ydHJhaXR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    ownerName: "Elena",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "Gold",
  },
  {
    id: 7,
    photo: ["https://hameleone.ru/wp-content/uploads/f/c/a/fca3c65d9e69bb86b79e914219284487.jpeg"],
    price: "35.00 BYN",
    guest: "2+2",
    room: "2 комн.",
    bed: "3",
    title: "Добрая половина выводов одухотворила всех причастных",
    address: "Московский р.",
    metro: "Молодёжная",
    route: "от Минска (км): 95",
    description:
      `Значимость этих проблем настолько очевидна, что убеждённость некоторых оппонентов представляет собой интересный эксперимент проверки благоприятных перспектив. Лишь сторонники тоталитаризма в науке являются только методом политического участия и подвергнуты целой серии независимых исследований. Но тщательные исследования конкурентов неоднозначны и будут разоблачены.`,
    ownerPhoto: "",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "",
  },
  {
    id: 8,
    photo: [],
    price: "90.00 BYN",
    guest: "3",
    room: "2 комн.",
    bed: "3",
    title: "Звук клавиш печатной машинки бодрит",
    address: "Октябрьский р.",
    metro: "Спортивная",
    route: "от Минска (км): 95",
    description:
      `Есть над чем задуматься: ключевые особенности структуры проекта и по сей день остаются уделом либералов, которые жаждут быть указаны как претенденты на роль ключевых факторов. Каждый из нас понимает очевидную вещь: экономическая повестка сегодняшнего дня создаёт необходимость включения в производственный план целого ряда внеочередных мероприятий с учётом комплекса своевременного выполнения сверхзадачи. Современные технологии достигли такого уровня, что современная методология разработки в значительной степени обусловливает важность позиций, занимаемых участниками в отношении поставленных задач.`,
    ownerPhoto: "",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "Gold",
  },
  {
    id: 9,
    photo: ["https://designmyhome.ru/sites/default/files/field/image/21/dizain_kvartir.jpg","https://maxmarket.com.ua/wp-content/uploads/2018/03/kvart.jpg", "https://budexim.com.ua/wp-content/uploads/2017/03/3.jpg"],
    price: "199.00 BYN",
    guest: "1",
    room: "1 комн.",
    bed: "1",
    title: "Тяжёлое машиностроение — это вам не старческий скрип Амстердама",
    address: "Октябрьский р.",
    metro: "Спортивная",
    route: "",
    description:
      `Предварительные выводы неутешительны: дальнейшее развитие различных форм деятельности создаёт необходимость включения в производственный план целого ряда внеочередных мероприятий с учётом комплекса своевременного выполнения сверхзадачи.`,
    ownerPhoto: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "",
  },
  {
    id: 10,
    photo: ["https://garmonia-s.com/wp-content/uploads/2020/12/Dizajn-interera-svetloy-smart-kvartiry-v-Odesse.jpg.jpg"],
    price: "300.00 BYN",
    guest: "2",
    room: "2 комн.",
    bed: "2",
    title: "Семантический разбор внешних противодействий так же органично вписывается в наши планы",
    address: "Партизанский р.",
    metro: "Кунцевщина",
    route: "",
    description:
      `Приятно, граждане, наблюдать, как базовые сценарии поведения пользователей формируют глобальную экономическую сеть и при этом — превращены в посмешище, хотя само их существование приносит несомненную пользу обществу.`,
    ownerPhoto: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "",
  },
  {
    id: 11,
    photo: ["https://tengrinews.kz/userdata/opinion/opinion_945/fd197bb3ce53e384e992727fdbe1af53.jpg"],
    price: "40.00 BYN",
    guest: "1",
    room: "1 комн.",
    bed: "1",
    title: "Да, средства индивидуальной защиты оказались бесполезны!",
    address: "Первомайский р.",
    metro: "Каменная горка",
    route: "",
    description:
      `В своём стремлении повысить качество жизни, они забывают, что понимание сути ресурсосберегающих технологий способствует подготовке и реализации первоочередных требований.`,
    ownerPhoto: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "",
  },
  {
    id: 12,
    photo: ["https://www.75c.com.ua/wp-content/uploads/2018/01/dizajn-interera-i-remont-kvartir-8.jpg","https://media.admagazine.ru/photos/6140a00358482ca8a11af5f4/16:9/w_1280,c_limit/_PREVIEW.jpg"],
    price: "500.00 BYN",
    guest: "4",
    room: "2 комн.",
    bed: "2",
    title: "Главные «СМИ» предупреждают: обучение кадров — приоритетная задача!",
    address: "Фрунзенский р.",
    metro: "Пролетарская",
    route: "",
    description:
      `Учитывая ключевые сценарии поведения, понимание сути ресурсосберегающих технологий способствует повышению качества направлений прогрессивного развития.`,
    ownerPhoto: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "",
  },
  {
    id: 13,
    photo: ["https://mykaleidoscope.ru/uploads/posts/2021-03/1615571923_51-p-shikarnii-remont-v-kvartire-53.jpg",
  "https://hameleone.ru/wp-content/uploads/f/c/a/fca3c65d9e69bb86b79e914219284487.jpeg"],
    price: "65.00 BYN",
    guest: "2+2",
    room: "1 комн.",
    bed: "3",
    title: "4-комн. апартаменты на Грушевке",
    address: "Заводской р.",
    metro: "Грушевка",
    route: "от Минска (км): 95",
    description:
      `Арендовать дом на сутки в Гомеле с баней и бассейном
в 5 минутах на машине от ЗИПа в усадьбе "Дом у реки". В доме 2-комнаты,
зал для гостей на 10 человек, кухня, ванная, 2 с/у на первом и втором этаже,
сауна, бассейн с холодной`,
    ownerPhoto: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "",
  
  },
  {
    id: 14,
    photo: ["https://euromedbud.com/wp-content/uploads/2022/04/remont-kvartyri-warshawa.jpg"],
    price: "130.00 BYN",
    guest: "2",
    room: "1 комн.",
    bed: "1",
    title: "1-комн. апартаменты на Грушевке",
    address: "Ленинский р.",
    metro: "Пушкинская",
    route: "от Минска (км): 35",
    description:
      `А ещё предприниматели в сети интернет представляют собой не что иное, как квинтэссенцию победы маркетинга над разумом и должны быть функционально разнесены на независимые элементы. Противоположная точка зрения подразумевает, что представители современных социальных резервов ассоциативно распределены по отраслям. Приятно, граждане, наблюдать, как представители современных социальных резервов представляют собой не что иное, как квинтэссенцию победы маркетинга над разумом и должны быть ассоциативно распределены по отраслям.`,
    ownerPhoto: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8cG9ydHJhaXR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    ownerName: "Elena",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "Gold",
  },
  {
    id: 15,
    photo: ["https://hameleone.ru/wp-content/uploads/f/c/a/fca3c65d9e69bb86b79e914219284487.jpeg"],
    price: "35.00 BYN",
    guest: "2+2",
    room: "2 комн.",
    bed: "3",
    title: "Добрая половина выводов одухотворила всех причастных",
    address: "Московский р.",
    metro: "Молодёжная",
    route: "от Минска (км): 95",
    description:
      `Значимость этих проблем настолько очевидна, что убеждённость некоторых оппонентов представляет собой интересный эксперимент проверки благоприятных перспектив. Лишь сторонники тоталитаризма в науке являются только методом политического участия и подвергнуты целой серии независимых исследований. Но тщательные исследования конкурентов неоднозначны и будут разоблачены.`,
    ownerPhoto: "",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "",
  },
  {
    id: 16,
    photo: [],
    price: "90.00 BYN",
    guest: "3",
    room: "2 комн.",
    bed: "3",
    title: "Звук клавиш печатной машинки бодрит",
    address: "Октябрьский р.",
    metro: "Спортивная",
    route: "от Минска (км): 95",
    description:
      `Есть над чем задуматься: ключевые особенности структуры проекта и по сей день остаются уделом либералов, которые жаждут быть указаны как претенденты на роль ключевых факторов. Каждый из нас понимает очевидную вещь: экономическая повестка сегодняшнего дня создаёт необходимость включения в производственный план целого ряда внеочередных мероприятий с учётом комплекса своевременного выполнения сверхзадачи. Современные технологии достигли такого уровня, что современная методология разработки в значительной степени обусловливает важность позиций, занимаемых участниками в отношении поставленных задач.`,
    ownerPhoto: "",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "Gold",
  },
  {
    id: 17,
    photo: ["https://mykaleidoscope.ru/uploads/posts/2021-03/1615571923_51-p-shikarnii-remont-v-kvartire-53.jpg",
  "https://hameleone.ru/wp-content/uploads/f/c/a/fca3c65d9e69bb86b79e914219284487.jpeg"],
    price: "65.00 BYN",
    guest: "2+2",
    room: "1 комн.",
    bed: "3",
    title: "4-комн. апартаменты на Грушевке",
    address: "Заводской р.",
    metro: "Грушевка",
    route: "от Минска (км): 95",
    description:
      `Арендовать дом на сутки в Гомеле с баней и бассейном
в 5 минутах на машине от ЗИПа в усадьбе "Дом у реки". В доме 2-комнаты,
зал для гостей на 10 человек, кухня, ванная, 2 с/у на первом и втором этаже,
сауна, бассейн с холодной`,
    ownerPhoto: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "",
  },
  {
    id: 18,
    photo: [],
    price: "130.00 BYN",
    guest: "2",
    room: "1 комн.",
    bed: "1",
    title: "1-комн. апартаменты на Грушевке",
    address: "Ленинский р.",
    metro: "Пушкинская",
    route: "от Минска (км): 35",
    description:
      `А ещё предприниматели в сети интернет представляют собой не что иное, как квинтэссенцию победы маркетинга над разумом и должны быть функционально разнесены на независимые элементы. Противоположная точка зрения подразумевает, что представители современных социальных резервов ассоциативно распределены по отраслям. Приятно, граждане, наблюдать, как представители современных социальных резервов представляют собой не что иное, как квинтэссенцию победы маркетинга над разумом и должны быть ассоциативно распределены по отраслям.`,
    ownerPhoto: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8cG9ydHJhaXR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    ownerName: "Elena",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "Gold",
  },
  {
    id: 19,
    photo: ["https://hameleone.ru/wp-content/uploads/f/c/a/fca3c65d9e69bb86b79e914219284487.jpeg"],
    price: "35.00 BYN",
    guest: "2+2",
    room: "2 комн.",
    bed: "3",
    title: "Добрая половина выводов одухотворила всех причастных",
    address: "Московский р.",
    metro: "Молодёжная",
    route: "от Минска (км): 95",
    description:
      `Значимость этих проблем настолько очевидна, что убеждённость некоторых оппонентов представляет собой интересный эксперимент проверки благоприятных перспектив. Лишь сторонники тоталитаризма в науке являются только методом политического участия и подвергнуты целой серии независимых исследований. Но тщательные исследования конкурентов неоднозначны и будут разоблачены.`,
    ownerPhoto: "",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "",
  },
  {
    id: 20,
    photo: [],
    price: "90.00 BYN",
    guest: "3",
    room: "2 комн.",
    bed: "3",
    title: "Звук клавиш печатной машинки бодрит",
    address: "Октябрьский р.",
    metro: "Спортивная",
    route: "от Минска (км): 95",
    description:
      `Есть над чем задуматься: ключевые особенности структуры проекта и по сей день остаются уделом либералов, которые жаждут быть указаны как претенденты на роль ключевых факторов. Каждый из нас понимает очевидную вещь: экономическая повестка сегодняшнего дня создаёт необходимость включения в производственный план целого ряда внеочередных мероприятий с учётом комплекса своевременного выполнения сверхзадачи. Современные технологии достигли такого уровня, что современная методология разработки в значительной степени обусловливает важность позиций, занимаемых участниками в отношении поставленных задач.`,
    ownerPhoto: "",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "Gold",
  },
  {
    id: 21,
    photo: ["https://designmyhome.ru/sites/default/files/field/image/21/dizain_kvartir.jpg","https://maxmarket.com.ua/wp-content/uploads/2018/03/kvart.jpg", "https://budexim.com.ua/wp-content/uploads/2017/03/3.jpg"],
    price: "199.00 BYN",
    guest: "1",
    room: "1 комн.",
    bed: "1",
    title: "Тяжёлое машиностроение — это вам не старческий скрип Амстердама",
    address: "Октябрьский р.",
    metro: "Спортивная",
    route: "",
    description:
      `Предварительные выводы неутешительны: дальнейшее развитие различных форм деятельности создаёт необходимость включения в производственный план целого ряда внеочередных мероприятий с учётом комплекса своевременного выполнения сверхзадачи.`,
    ownerPhoto: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "",
  },
  {
    id: 22,
    photo: ["https://garmonia-s.com/wp-content/uploads/2020/12/Dizajn-interera-svetloy-smart-kvartiry-v-Odesse.jpg.jpg"],
    price: "300.00 BYN",
    guest: "2",
    room: "2 комн.",
    bed: "2",
    title: "Семантический разбор внешних противодействий так же органично вписывается в наши планы",
    address: "Партизанский р.",
    metro: "Кунцевщина",
    route: "",
    description:
      `Приятно, граждане, наблюдать, как базовые сценарии поведения пользователей формируют глобальную экономическую сеть и при этом — превращены в посмешище, хотя само их существование приносит несомненную пользу обществу.`,
    ownerPhoto: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "",
  },
  {
    id: 23,
    photo: ["https://tengrinews.kz/userdata/opinion/opinion_945/fd197bb3ce53e384e992727fdbe1af53.jpg"],
    price: "40.00 BYN",
    guest: "1",
    room: "1 комн.",
    bed: "1",
    title: "Да, средства индивидуальной защиты оказались бесполезны!",
    address: "Первомайский р.",
    metro: "Каменная горка",
    route: "",
    description:
      `В своём стремлении повысить качество жизни, они забывают, что понимание сути ресурсосберегающих технологий способствует подготовке и реализации первоочередных требований.`,
    ownerPhoto: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "",
  },
  {
    id: 24,
    photo: ["https://www.75c.com.ua/wp-content/uploads/2018/01/dizajn-interera-i-remont-kvartir-8.jpg","https://media.admagazine.ru/photos/6140a00358482ca8a11af5f4/16:9/w_1280,c_limit/_PREVIEW.jpg"],
    price: "500.00 BYN",
    guest: "4",
    room: "2 комн.",
    bed: "2",
    title: "Главные «СМИ» предупреждают: обучение кадров — приоритетная задача!",
    address: "Фрунзенский р.",
    metro: "Пролетарская",
    route: "",
    description:
      `Учитывая ключевые сценарии поведения, понимание сути ресурсосберегающих технологий способствует повышению качества направлений прогрессивного развития.`,
    ownerPhoto: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "",
  },
  {
    id: 25,
    photo: ["https://mykaleidoscope.ru/uploads/posts/2021-03/1615571923_51-p-shikarnii-remont-v-kvartire-53.jpg",
  "https://hameleone.ru/wp-content/uploads/f/c/a/fca3c65d9e69bb86b79e914219284487.jpeg"],
    price: "65.00 BYN",
    guest: "2+2",
    room: "1 комн.",
    bed: "3",
    title: "4-комн. апартаменты на Грушевке",
    address: "Заводской р.",
    metro: "Грушевка",
    route: "от Минска (км): 95",
    description:
      `Арендовать дом на сутки в Гомеле с баней и бассейном
в 5 минутах на машине от ЗИПа в усадьбе "Дом у реки". В доме 2-комнаты,
зал для гостей на 10 человек, кухня, ванная, 2 с/у на первом и втором этаже,
сауна, бассейн с холодной`,
    ownerPhoto: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "",
  
  },
  {
    id: 26,
    photo: ["https://euromedbud.com/wp-content/uploads/2022/04/remont-kvartyri-warshawa.jpg"],
    price: "130.00 BYN",
    guest: "2",
    room: "1 комн.",
    bed: "1",
    title: "1-комн. апартаменты на Грушевке",
    address: "Ленинский р.",
    metro: "Пушкинская",
    route: "от Минска (км): 35",
    description:
      `А ещё предприниматели в сети интернет представляют собой не что иное, как квинтэссенцию победы маркетинга над разумом и должны быть функционально разнесены на независимые элементы. Противоположная точка зрения подразумевает, что представители современных социальных резервов ассоциативно распределены по отраслям. Приятно, граждане, наблюдать, как представители современных социальных резервов представляют собой не что иное, как квинтэссенцию победы маркетинга над разумом и должны быть ассоциативно распределены по отраслям.`,
    ownerPhoto: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8cG9ydHJhaXR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    ownerName: "Elena",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "Gold",
  },
  {
    id: 27,
    photo: ["https://hameleone.ru/wp-content/uploads/f/c/a/fca3c65d9e69bb86b79e914219284487.jpeg"],
    price: "35.00 BYN",
    guest: "2+2",
    room: "2 комн.",
    bed: "3",
    title: "Добрая половина выводов одухотворила всех причастных",
    address: "Московский р.",
    metro: "Молодёжная",
    route: "от Минска (км): 95",
    description:
      `Значимость этих проблем настолько очевидна, что убеждённость некоторых оппонентов представляет собой интересный эксперимент проверки благоприятных перспектив. Лишь сторонники тоталитаризма в науке являются только методом политического участия и подвергнуты целой серии независимых исследований. Но тщательные исследования конкурентов неоднозначны и будут разоблачены.`,
    ownerPhoto: "",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "",
  },
  {
    id: 28,
    photo: [],
    price: "90.00 BYN",
    guest: "3",
    room: "2 комн.",
    bed: "3",
    title: "Звук клавиш печатной машинки бодрит",
    address: "Октябрьский р.",
    metro: "Спортивная",
    route: "от Минска (км): 95",
    description:
      `Есть над чем задуматься: ключевые особенности структуры проекта и по сей день остаются уделом либералов, которые жаждут быть указаны как претенденты на роль ключевых факторов. Каждый из нас понимает очевидную вещь: экономическая повестка сегодняшнего дня создаёт необходимость включения в производственный план целого ряда внеочередных мероприятий с учётом комплекса своевременного выполнения сверхзадачи. Современные технологии достигли такого уровня, что современная методология разработки в значительной степени обусловливает важность позиций, занимаемых участниками в отношении поставленных задач.`,
    ownerPhoto: "",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "Gold",
  },
  {
    id: 29,
    photo: ["https://mykaleidoscope.ru/uploads/posts/2021-03/1615571923_51-p-shikarnii-remont-v-kvartire-53.jpg",
  "https://hameleone.ru/wp-content/uploads/f/c/a/fca3c65d9e69bb86b79e914219284487.jpeg"],
    price: "65.00 BYN",
    guest: "2+2",
    room: "1 комн.",
    bed: "3",
    title: "4-комн. апартаменты на Грушевке",
    address: "Заводской р.",
    metro: "Грушевка",
    route: "от Минска (км): 95",
    description:
      `Арендовать дом на сутки в Гомеле с баней и бассейном
в 5 минутах на машине от ЗИПа в усадьбе "Дом у реки". В доме 2-комнаты,
зал для гостей на 10 человек, кухня, ванная, 2 с/у на первом и втором этаже,
сауна, бассейн с холодной`,
    ownerPhoto: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "",
  },
  {
    id: 30,
    photo: [],
    price: "130.00 BYN",
    guest: "2",
    room: "1 комн.",
    bed: "1",
    title: "1-комн. апартаменты на Грушевке",
    address: "Ленинский р.",
    metro: "Пушкинская",
    route: "от Минска (км): 35",
    description:
      `А ещё предприниматели в сети интернет представляют собой не что иное, как квинтэссенцию победы маркетинга над разумом и должны быть функционально разнесены на независимые элементы. Противоположная точка зрения подразумевает, что представители современных социальных резервов ассоциативно распределены по отраслям. Приятно, граждане, наблюдать, как представители современных социальных резервов представляют собой не что иное, как квинтэссенцию победы маркетинга над разумом и должны быть ассоциативно распределены по отраслям.`,
    ownerPhoto: "https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8cG9ydHJhaXR8ZW58MHx8MHx8&auto=format&fit=crop&w=500&q=60",
    ownerName: "Elena",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "Gold",
  },
  {
    id: 31,
    photo: ["https://hameleone.ru/wp-content/uploads/f/c/a/fca3c65d9e69bb86b79e914219284487.jpeg"],
    price: "35.00 BYN",
    guest: "2+2",
    room: "2 комн.",
    bed: "3",
    title: "Добрая половина выводов одухотворила всех причастных",
    address: "Московский р.",
    metro: "Молодёжная",
    route: "от Минска (км): 95",
    description:
      `Значимость этих проблем настолько очевидна, что убеждённость некоторых оппонентов представляет собой интересный эксперимент проверки благоприятных перспектив. Лишь сторонники тоталитаризма в науке являются только методом политического участия и подвергнуты целой серии независимых исследований. Но тщательные исследования конкурентов неоднозначны и будут разоблачены.`,
    ownerPhoto: "",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "",
  },
  {
    id: 32,
    photo: [],
    price: "90.00 BYN",
    guest: "3",
    room: "2 комн.",
    bed: "3",
    title: "Звук клавиш печатной машинки бодрит",
    address: "Октябрьский р.",
    metro: "Спортивная",
    route: "от Минска (км): 95",
    description:
      `Есть над чем задуматься: ключевые особенности структуры проекта и по сей день остаются уделом либералов, которые жаждут быть указаны как претенденты на роль ключевых факторов. Каждый из нас понимает очевидную вещь: экономическая повестка сегодняшнего дня создаёт необходимость включения в производственный план целого ряда внеочередных мероприятий с учётом комплекса своевременного выполнения сверхзадачи. Современные технологии достигли такого уровня, что современная методология разработки в значительной степени обусловливает важность позиций, занимаемых участниками в отношении поставленных задач.`,
    ownerPhoto: "",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "Gold",
  },
  {
    id: 33,
    photo: ["https://designmyhome.ru/sites/default/files/field/image/21/dizain_kvartir.jpg","https://maxmarket.com.ua/wp-content/uploads/2018/03/kvart.jpg", "https://budexim.com.ua/wp-content/uploads/2017/03/3.jpg"],
    price: "199.00 BYN",
    guest: "1",
    room: "1 комн.",
    bed: "1",
    title: "Тяжёлое машиностроение — это вам не старческий скрип Амстердама",
    address: "Октябрьский р.",
    metro: "Спортивная",
    route: "",
    description:
      `Предварительные выводы неутешительны: дальнейшее развитие различных форм деятельности создаёт необходимость включения в производственный план целого ряда внеочередных мероприятий с учётом комплекса своевременного выполнения сверхзадачи.`,
    ownerPhoto: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "",
  },
  {
    id: 34,
    photo: ["https://garmonia-s.com/wp-content/uploads/2020/12/Dizajn-interera-svetloy-smart-kvartiry-v-Odesse.jpg.jpg"],
    price: "300.00 BYN",
    guest: "2",
    room: "2 комн.",
    bed: "2",
    title: "Семантический разбор внешних противодействий так же органично вписывается в наши планы",
    address: "Партизанский р.",
    metro: "Кунцевщина",
    route: "",
    description:
      `Приятно, граждане, наблюдать, как базовые сценарии поведения пользователей формируют глобальную экономическую сеть и при этом — превращены в посмешище, хотя само их существование приносит несомненную пользу обществу.`,
    ownerPhoto: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "",
  },
  {
    id: 35,
    photo: ["https://tengrinews.kz/userdata/opinion/opinion_945/fd197bb3ce53e384e992727fdbe1af53.jpg"],
    price: "40.00 BYN",
    guest: "1",
    room: "1 комн.",
    bed: "1",
    title: "Да, средства индивидуальной защиты оказались бесполезны!",
    address: "Первомайский р.",
    metro: "Каменная горка",
    route: "",
    description:
      `В своём стремлении повысить качество жизни, они забывают, что понимание сути ресурсосберегающих технологий способствует подготовке и реализации первоочередных требований.`,
    ownerPhoto: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "",
  },
  {
    id: 36,
    photo: ["https://www.75c.com.ua/wp-content/uploads/2018/01/dizajn-interera-i-remont-kvartir-8.jpg","https://media.admagazine.ru/photos/6140a00358482ca8a11af5f4/16:9/w_1280,c_limit/_PREVIEW.jpg"],
    price: "500.00 BYN",
    guest: "4",
    room: "2 комн.",
    bed: "2",
    title: "Главные «СМИ» предупреждают: обучение кадров — приоритетная задача!",
    address: "Фрунзенский р.",
    metro: "Пролетарская",
    route: "",
    description:
      `Учитывая ключевые сценарии поведения, понимание сути ресурсосберегающих технологий способствует повышению качества направлений прогрессивного развития.`,
    ownerPhoto: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=774&q=80",
    ownerName: "Dmitriy",
    ownerNumber: "+375 (29) 291-14-44",
    ownerEmail: "vladimir6234@tut.by",
    label: "",
  },
  
]